version: '3.3'

services:
  app:
    container_name: example
    image: example_php
    build: build/php
    volumes:
      - ../:/var/www/html
    ports:
      - 8000:80
    environment:
      - NETTE_DEBUG=1
      - COMPOSER_AUTH=${COMPOSER_AUTH}
    links:
      - database

  database:
    container_name: example_db
    image: example_db
    build: build/database
    ports:
      - 3307:3306
    environment:
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./build/database/01_articles.sql:/docker-entrypoint-initdb.d/01_articles.sql
      - ./build/database/02_comments.sql:/docker-entrypoint-initdb.d/02_comments.sql

  adminer:
    command: "php -S 0.0.0.0:8080"
    container_name: adminer
    image: adminer
    ports:
      - 81:8080
    depends_on:
      - database
